### ISSUE TITLE
Mac installer fails on non-existant directory

### ISSUE THREAD

**Issue by boyarsky** [wpilibsuite/WPILibInstaller-Avalonia#100]
When I tried to install with single VS Code, the installer failed with:
```
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunScriptExecutable(String script, Int32 timeoutMs, String[] args) in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 497
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunToolSetup() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 514
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunInstall() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 103
   at WPILibInstaller.ViewModels.InstallPageViewModel.<>c__DisplayClass16_0.<<-ctor>g__installFunc|0>d.MoveNext() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 67
```

When I tried with skip VS code, it failed with
```
System.TypeLoadException: Could not load type 'Avalonia.Markup.Xaml.MarkupExtensions.BindingExtension' from assembly 'Avalonia.Markup.Xaml, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'.
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.!XamlIlPopulate(IServiceProvider , MsBoxStandardWindow )
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.!XamlIlPopulateTrampoline(MsBoxStandardWindow )
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxStandardWindow..ctor(Style style)
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(MessageBoxStandardParams params)
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(String title, String text, ButtonEnum enum, Icon icon, Style style)
   at WPILibInstaller.ViewModels.VSCodePageViewModel.SkipVsCodeFunc() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs:line 143
```

My user directory is /Users/nyjeanne. There is no /Users/runner. I don't know where it is getting that from.

I don't think is relevant, but I had to right click and choose open to get around the Apple cannot check for malicious software/verify the identity of the developer.

**Comment by AustinShalit** [comment]
If you open a terminal and type `python3 --version` what is the output?

What version of macOS are you using?

What version of the installer are you using?

**Comment by boyarsky** [comment]
Austin,
I'm on Python 3.4.2, Mac Mojave and the WPILIb Beta 1 (2021) version of the installer.

I can upgrade Python to current if you'd like me to try that. There's nothing special about 3.4.2. That was the version that was current last time I did something substantial with Python :).

**Comment by ThadHouse** [comment]
The directory shown is where the app was compiled on, so has no relation to where things are being installed.

**Comment by prateekma** [comment]
Can you drag just the application out of the dmg, run the following, and paste the output?
`spctl -a -t install -vvvv WPILibInstaller.app`

**Comment by boyarsky** [comment]
@ThadHouse  ok then I won't fixate on the path. It's still broken though :).
@prateekma here you do:
```
nyjeanne$ spctl -a -t install -vvvv WPILibInstaller.app
WPILibInstaller.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Brad Miller (58SET3NSX7)
```

**Comment by prateekma** [comment]
Hm, then I'm not sure why your Mac won't open it -- that message means that the app is notarized and Gatekeeper should be okay with it.

Can you run `ls ~/wpilib/2021/tools` and provide that output?

**Comment by prateekma** [comment]
Furthermore, can you also run: `/usr/bin/python3 --version`?

**Comment by boyarsky** [comment]
@prateekma  Interesting. So it did start installing.

nyjeanne$ ls ~/wpilib/2021/tools
ScriptBase.py		ToolsUpdater.jar	tools.json
ScriptBase.vbs		ToolsUpdater.py


nyjeanne$ /usr/bin/python3 --version
-bash: /usr/bin/python3: No such file or directory

nyjeanne$ which python3
/Library/Frameworks/Python.framework/Versions/3.4/bin/python3

**Comment by prateekma** [comment]
I believe the C# is looking in /usr/bin which is why you're getting that error. I don't know if Mojave doesn't have a `/usr/bin/python3` in general or if it is something weird on your system. So far, we've only tested this on Big Sur and Catalina.

Can you try adding that directory to PATH and rerunning?

**Comment by boyarsky** [comment]
python3 is already on the path. Do you want me to add a /usr/bin/python3 symlink to it and test that?

**Comment by prateekma** [comment]
If that is possible, it would help.

**Comment by boyarsky** [comment]
I added the symlink to /usr/local/bin rather than /usr/bin because I got a permissions error and [SO](https://stackoverflow.com/questions/36730549/cannot-create-a-symlink-inside-of-usr-bin-even-as-sudo) makes it sound non-trivial to add. Also [this page](https://opensource.com/article/19/5/python-3-default-mac) suggests I should have a /usr/local/bin link rather than a /usr/bin link.

nyjeanne$ /usr/local/bin/python3 --version
Python 3.4.2

No change in behavior. (I haven't upgraded to Catalina yet because I'm worried something will go wrong and I don't want to be without my computer in a pandemic)

**Comment by prateekma** [comment]
Hm, `/usr/local/bin` should be in the global PATH so I'm not sure why it can't find it. Once #95 is merged, it should automatically find the correct Python to run with even on Mojave.

**Comment by sciencewhiz** [comment]
@boyarsky can you confirm the beta 2 installer worked?
