### ISSUE TITLE
[BUG] Linux font family error

### ISSUE THREAD

**Issue by RyanHir** [wpilibsuite/WPILibInstaller-Avalonia#153]
Program will only work if the base MS fonts are installed and will crash if not included on system.

 * Work Around:
   * Arch: install `ttf-ms-fonts` from the AUR.
   * Debian/Ubuntu: install `ttf-mscorefonts-installer` from the repos

 * Crash Log
```
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.Media.TextFormatting.TextCharacters.TryGetRunProperties(ReadOnlySlice`1 text, Typeface typeface, Typeface defaultTypeface, Int32& count)
   at Avalonia.Media.TextFormatting.TextCharacters.CreateShapeableRun(ReadOnlySlice`1 text, TextRunProperties defaultProperties)
   at Avalonia.Media.TextFormatting.TextCharacters.GetShapeableCharacters()
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextLineBreak previousLineBreak, TextLineBreak& nextLineBreak)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak)
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout()
   at Avalonia.Media.TextFormatting.TextLayout..ctor(String text, Typeface typeface, Double fontSize, IBrush foreground, TextAlignment textAlignment, TextWrapping textWrapping, TextTrimming textTrimming, TextDecorationCollection textDecorations, Double maxWidth, Double maxHeight, Double lineHeight, Int32 maxLines, IReadOnlyList`1 textStyleOverrides)
   at Avalonia.Controls.TextBlock.CreateTextLayout(Size constraint, String text)
   at Avalonia.Controls.TextBlock.get_TextLayout()
   at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Threading.Dispatcher.RunJobs(DispatcherPriority minimumPriority)
   at Avalonia.X11.X11Window.<OnEventSync>b__104_1()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at WPILibInstaller.Program.Main(String[] args)
Aborted (core dumped)
```

**Comment by ThadHouse** [comment]
We never saw this during any testing, with multiple people testing both arch and debian installs, both stock and ones that had been used for a while. Its possible this is likely a configuration issue with your system, and installing those fonts just reconfigures some things. We can put a note in somewhere, but likely nothing we can do to fix it from our end.

**Comment by RyanHir** [comment]
I understand, I am using a minimal installation so I don't have much fonts installed. From what I read online Avalonia defaults to MS fonts and I presume Gnome/KDE installations put a MS font shim for compatibility which allows for it to work in the tests.

**Comment by RyanHir** [comment]
My understanding of Avalonia is limited but from what I have seen, it is possible to embed fonts into the package. This would allow for greater compatibility if a open licensed font is embedded into the installation.

**Comment by calcmogul** [comment]
I don't have msfonts installed and it works for me on Arch. SkiaSharp is picking up a different default font for me. After doing the following on Arch:

```bash
sudo pacman -S skia-sharp
dotnet new console fonttest
```

Then edit `fonttest/Program.cs` with the following file adapted from https://github.com/AvaloniaUI/Avalonia/issues/4427#issuecomment-668123755

```csharp
using System;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            System.Console.WriteLine("1st printout");
            System.Console.Write("SkiaSharp.SKTypeface.Default.FamilyName=");
            System.Console.WriteLine(SkiaSharp.SKTypeface.Default.FamilyName);
            System.Console.Write("SkiaSharp.SKFontManager.Default.MatchFamily(null)=");
            System.Console.WriteLine(SkiaSharp.SKFontManager.Default.MatchFamily(null));
            System.Console.Write("SkiaSharp.SKFontManager.Default.MatchFamily(string.Empty)=");
            System.Console.WriteLine(SkiaSharp.SKFontManager.Default.MatchFamily(string.Empty));
            System.Console.Write("SkiaSharp.SKFontManager.Default.MatchFamily(\"sans\")=");
            System.Console.WriteLine(SkiaSharp.SKFontManager.Default.MatchFamily("sans"));
            System.Console.WriteLine("1st printout - done");
        }
    }
}
```

Then run with `dotnet run`, I get the following output:

```
SkiaSharp.SKTypeface.Default.FamilyName=DejaVu Sans
SkiaSharp.SKFontManager.Default.MatchFamily(null)=SkiaSharp.SKTypeface+SKTypefaceStatic
SkiaSharp.SKFontManager.Default.MatchFamily(string.Empty)=
SkiaSharp.SKFontManager.Default.MatchFamily("sans")=SkiaSharp.SKTypeface+SKTypefaceStatic
```

**Comment by ShannonZ** [comment]
I‘ve installed ttf-mscorefonts-installer and refresh the font cache. But I still get the same error.

**Comment by calcmogul** [comment]
Not surprising since that suggested fix for Ubuntu was never tested (the OP runs Arch).

**Comment by RyanHir** [comment]
Correct, it was presumed not tested. If you want to attempt installation via CLI, try these instructions https://github.com/wpilibsuite/WPILibInstaller-Avalonia/issues/11#issuecomment-747858502

**Comment by RyanHir** [comment]
I'm closing this as the issue appears to have resolved itself and I am now using a combination of Windows & Ubuntu.

**Comment by ErdajtSopjani** [comment]
This fixed the issue for me! Thanks.
