### ISSUE TITLE
WPILIB Instillation Error

### ISSUE THREAD

**Issue by sai-raparla** [wpilibsuite/WPILibInstaller-Avalonia#161]
I keep getting this error when trying to download the latest WPILIB without Vs code cause I already have it installed. What do I do?

System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WPILibInstaller.ViewModels.InstallPageViewModel.<>c__DisplayClass43_0.<RunVsCodeExtensionsSetup>b__8() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 580
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunVsCodeExtensionsSetup() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 578
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunInstall() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 135
   at WPILibInstaller.ViewModels.InstallPageViewModel.<>c__DisplayClass24_0.<<-ctor>g__installFunc|0>d.MoveNext() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 72

**Comment by sciencewhiz** [comment]
The installer only supports the 2021WPILIb VS Code installation. It will throw that error if you haven't previously installed VS code using the 2021 WPILib installer.

![image](https://user-images.githubusercontent.com/4885091/107724676-45b1ac00-6c99-11eb-930d-56aa763bf1bf.png)

**Comment by sai-raparla** [comment]
Oh so does that mean I need to install a new vs code? I already have one.

**Comment by sai-raparla** [comment]
Actually never mind I understand.
