### ISSUE TITLE
Windows7 corrupt cmd.exe: Installation failed! The error is below. Presh finish to exit.

### ISSUE THREAD

**Issue by tautred** [wpilibsuite/WPILibInstaller-Avalonia#162]
I keep getting the following error. I downloaded and installed VS Code and can install most components, but get this error on "WPILib Dependencies" or "Visual Studio Code Extensions". Have I missed a step?

System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunScriptExecutable(String script, Int32 timeoutMs, String[] args)
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunMavenMetaDataFixer()
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunInstall()
   at WPILibInstaller.ViewModels.InstallPageViewModel.<>c__DisplayClass24_0.<<-ctor>g__installFunc|0>d.MoveNext()

**Comment by ThadHouse** [comment]
You also left the JDK checked, correct? It has to be checked for those to work. If you do have it checked, we've sometime seen this happen if your system is broken and cant run bash scripts. Are you able to launch a cmd prompt? Assuming yes to that, in C:\Users\Public\wpilib\2020\maven can you run MavenMetaDataFixer.bat from that command prompt?

**Comment by ThadHouse** [comment]
Another thing to note is we do no testing on Windows 7 anymore. It should work, but being out of support makes it hard for us to support it. Happy to help try and debug, but we can't guarantee it will work in future years.

**Comment by tautred** [comment]
I think this is my fault. cmd.exe was corrupted - I'm fixing that now and will close this issue if that's the issue.

And yes, it's an old Windows 7 laptop as I'm visiting a team who can't find theirs.

Thanks for the super quick response.

**Comment by tautred** [comment]
FTR, installing wpilib from VS Code showed up the error with cmd.exe - it's certainly not something you should have to deal with :-)

**Comment by tautred** [comment]
cmd.exe replaced - all working fine.
