### ISSUE TITLE
WPILIB 2021.2.2 installation error: Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by FRC6302** [wpilibsuite/WPILibInstaller-Avalonia#163]
I am trying to install WPILIB 2021.2.2 and installation fails every time with this error: 

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at WPILibInstaller.ViewModels.InstallPageViewModel.SetIfNotSet[T](String key, T value, Object settingsJson)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at WPILibInstaller.ViewModels.InstallPageViewModel.ConfigureVsCodeSettings()
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunInstall()
   at WPILibInstaller.ViewModels.InstallPageViewModel.<>c__DisplayClass24_0.<<-ctor>g__installFunc|0>d.MoveNext()

I am not very knowledgeable about this kind of stuff, so if you could keep explanations simple that would be great. Thanks!

**Comment by ThadHouse** [comment]
2 questions. 1st, which platform. And 2nd you didn't skip VS Code install, correct?

**Comment by FRC6302** [comment]
> 2 questions. 1st, which platform. And 2nd you didn't skip VS Code install, correct?

I am using Windows 64. And it happens regardless of whether I skip VS code install

**Comment by ThadHouse** [comment]
Ok, I wonder if something got messed up. Can you go to 

C:\users\public\wpilib\2021\vscode\data\user-data\User

and delete settings.json. And then try again?

**Comment by FRC6302** [comment]
This worked. Thanks!
