### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by jlschulz** [wpilibsuite/WPILibInstaller-Avalonia#165]
Hello,

Per the installation instructions, we were able to mount the WPILib installer disk image and ran the installer EXE file. (using WPILib_Windows64-2021.2.2.iso, installing on Windows 10).

After clicking 'Start' on the initial screen, we selected the 'Download VS Code for Single Install' and received the error below. We also received the error when we attempted the 'Download VS Code for Offline Install' option.

Any thoughts on what might be causing this?

Error message:

System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at WPILibInstaller.Utils.HttpClientDownloadWithProgress.DownloadFileFromHttpResponseMessage(HttpResponseMessage response, CancellationToken token)
   at WPILibInstaller.Utils.HttpClientDownloadWithProgress.StartDownload(CancellationToken token)
   at WPILibInstaller.ViewModels.VSCodePageViewModel.DownloadForPlatform(String downloadUrl, Stream outputStream, CancellationToken token, Action`1 progressChanged)
   at WPILibInstaller.ViewModels.VSCodePageViewModel.DownloadToMemoryStream(Platform platform, String downloadUrl, CancellationToken token, Action`1 progressChanged)
   at WPILibInstaller.ViewModels.VSCodePageViewModel.DownloadSingleVSCodeFunc()

**Comment by prateekma** [comment]
Please see this CD post: https://www.chiefdelphi.com/t/wpilib-install-cannot-download-vscode/392750/5?u=prateek_m

We recently fixed this issue and new builds are available on the allwpilib repo.

**Comment by sciencewhiz** [comment]
https://docs.wpilib.org/en/stable/docs/yearly-overview/known-issues.html#no-such-host-is-known-in-the-wpilib-installer

**Comment by jlschulz** [comment]
Thanks!

VS is installing now.
