### ISSUE TITLE
Install fails when updating from 2022.1.1 to 2022.2.1 on Mac

### ISSUE THREAD

**Issue by WiiHaveFun** [wpilibsuite/WPILibInstaller-Avalonia#244]
The installer downloads all necessary files, but the installation ends with this error. I'm running on macOS Monterey 12.1.
When I opened VScode, I was prompted to update to 2022.2.1. After, I was able to see the project is running on the latest version. I haven't had the chance to see if my robot code and WPIlib works on a robot, but my project does build successfully. Is there a serious problem here or am I fine to continue developing in 2022.2.1. Thanks!

System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WPILibInstaller.ViewModels.InstallPageViewModel.<>c__DisplayClass45_0.<RunVsCodeExtensionsSetup>b__8() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 666
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunVsCodeExtensionsSetup() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 664
   at WPILibInstaller.ViewModels.InstallPageViewModel.InstallEverything(CancellationToken token) in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 160
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunInstall() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 191
   at WPILibInstaller.ViewModels.InstallPageViewModel.<>c__DisplayClass24_0.<<-ctor>g__installFunc|0>d.MoveNext() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 73

**Comment by ThadHouse** [comment]
You didn't rename your FRC VS Code instance, right? Thats what causes this error, if you do that and then skip installing VS Code during the update. Basically this error is VS Code failing to be found.

**Comment by WiiHaveFun** [comment]
My VS Code instance defaulted to "Visual Studio Code 2022" since I have still have WPIlib from 2020 and 2021. Should I rename it to "Visual Studio Code"?

**Comment by ThadHouse** [comment]
The VS Code instance should have installed into ~/wpilib/2022 when you originally installed, and yes you do not want to rename that. Thats what causes this issue.

**Comment by WiiHaveFun** [comment]
I just ran my installer again with the VScode instance named as "Visual Studio Code 2022" and the same error occurred.

**Comment by ThadHouse** [comment]
It should just be named "Visual Studio Code"

**Comment by WiiHaveFun** [comment]
Got it! I was a bit confused there. It looks like when I have multiple versions of WPIlib installed from previous years, the viscose installer names it with the current year. Let me run it again.

**Comment by WiiHaveFun** [comment]
Finished perfectly, thank you for the help!
