### ISSUE TITLE
WPILib 2023.1.1 Beta 2 macOS Installation Failed

### ISSUE THREAD

**Issue by lhvy** [wpilibsuite/WPILibInstaller-Avalonia#284]
After downloading the latest artifact generated by CI (due to recent fix merged in #283), and running `sudo xattr -d com.apple.quarantine /Users/Lucas/Downloads/WPILibInstaller.app` because Apple certificates presumably have expired, the installer runs, but fails whilst installing with the following error:

```
System.DllNotFoundException: Unable to load shared library 'MonoPosixHelper' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMonoPosixHelper, 0x0001): tried: 'libMonoPosixHelper' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibMonoPosixHelper' (no such file), '/usr/lib/libMonoPosixHelper' (no such file, not in dyld cache), 'libMonoPosixHelper' (no such file), '/usr/local/lib/libMonoPosixHelper' (no such file), '/usr/lib/libMonoPosixHelper' (no such file, not in dyld cache)
   at Mono.Unix.Native.Syscall.stat(String file_name, Stat& buf)
   at WPILibInstaller.ViewModels.InstallPageViewModel.ExtractArchive(CancellationToken token, String[] filter) in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 562
   at WPILibInstaller.ViewModels.InstallPageViewModel.InstallEverything(CancellationToken token) in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 132
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunInstall() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 191
   at WPILibInstaller.ViewModels.InstallPageViewModel.<>c__DisplayClass24_0.<<-ctor>g__installFunc|0>d.MoveNext() in /Users/runner/work/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs:line 73
```

I can confirm that `~/wpilib/2023` is created during the install, but only `installUtils` and `maven` folders are created before the error occurs, and neither folder contains more than 2 files.

**Comment by ThadHouse** [comment]
Yup. Thats going to be a problem too... I'll have to figure out how to fix that.
