### ISSUE TITLE
NoSuchFileException errors on Linux

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/WPILibInstaller-Avalonia#431]
Installing on Linux succeeds, but results in multiple of the following errors being printed to console.  This is likely due to #427.

```
Installing DataLogTool
java.nio.file.NoSuchFileException: /home/peter/wpilib/2025/tools/ScriptBaseCpp.vbs
java.nio.file.NoSuchFileException: /home/peter/wpilib/2025/tools/ScriptBaseCpp.vbs
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
        at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
        at java.base/java.nio.file.Files.copy(Files.java:1305)
        at Program.installCppTool(Program.java:83)
        at Program.lambda$main$1(Program.java:130)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at Program.main(Program.java:124)
```

**Comment by sciencewhiz** [comment]
Yes, https://github.com/wpilibsuite/WPILibInstaller-Avalonia/blob/b1569ad2a536730308c35cc92d257cb22616b7d7/apps/ToolsUpdater/src/main/java/Program.java also needs to be platform aware.

**Comment by PeterJohnson** [comment]
@Gold856
