### ISSUE TITLE
Installer crashes when trying to skip VS Code install

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/WPILibInstaller-Avalonia#81]
Stacktrace:
```
System.TypeLoadException
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.!XamlIlPopulate(IServiceProvider , MsBoxStandardWindow )
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.!XamlIlPopulateTrampoline(MsBoxStandardWindow )
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxStandardWindow..ctor(Style style)
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(MessageBoxStandardParams params)
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(String title, String text, ButtonEnum enum, Icon icon, Style style)
   at WPILibInstaller.ViewModels.VSCodePageViewModel.SkipVsCodeFunc()
```

Reproduction steps: 
1. when asked to select how to install VS Code (the first screen after start), select `Skip installing VS Code`.

**Comment by Starlight220** [comment]
I found another crash-inducing bug in the installer, details on TeamForge. If it should be reported here, I'll open another issue.

**Comment by ThadHouse** [comment]
I created #83 for that other issue. And we'll update the docs to make it clearer what that button does. Just like previous seasons, we don't support installing into a global vscode.
